### ISSUE TITLE
Feature request: Content indexing

### ISSUE THREAD

**Issue by jlg89** [alfredapp/google-drive-workflow#38]
It wouldn't surprise me if there's a technical limitation that would prevent content indexing, but it's worth asking the question.

**Comment by vitorgalvao** [comment]
It would be impossible for most files, because they’re not really stored locally (so can’t access their contents). For the others, it would still create a ginormous cache. Spotlight indexing [may be coming back](https://support.google.com/drive/answer/12178485#zippy=%2Chow-does-this-functionality-differ-from-what-i-had-before) to Google Drive, though it’s still unclear to which extent.
