### ISSUE TITLE
Add support for Google Drive shortcuts

### ISSUE THREAD

**Issue by SimonGZ** [alfredapp/google-drive-workflow#39]
### Workflow version
2022.11

### Alfred version
4.6.6

### macOS version
12.3.1

### Architecture
arm64

### Workflow environment variables
Dict {
    ignore_list = 
    result_limit = 50
    auto_refresh = 1
    google_drive_path = /Volumes/GoogleDrive/My Drive
}

### Full Disk Access
Granted

### Google drive paths
Exists: /Volumes/GoogleDrive/My Drive
611 paths

### Cache dir
cache.db

### Cache file
16777234 35422907 -rw-r--r-- 1 simong staff 0 77824 "Jun 15 11:21:22 2022" "Jun 15 11:21:19 2022" "Jun 15 11:21:19 2022" "Jun 15 11:21:18 2022" 4096 152 0 /Users/simong/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.alfredapp.googledrive/cache.db

### Temporary cache
Does NOT exist

### Build progress
NOT running

### Launchd job
Loaded: -	0	com.alfredapp.googledrive
Installed

### Debugger output

```codeblock
N/A
```

### More details

Google recently switched my account over to their new "Shortcuts" model where files can no longer exist in multiple folders. It now works much more like aliases/symbolic links and thus a lot of folders in my Google Drive have become shortcuts. ( More information here: https://support.google.com/drive/answer/10864219?hl=en )

Unfortunately, I don't think the current version of the workflow understands these new shortcuts, so anything that's in a shortcut folder doesn't appear in the results.

**Comment by vitorgalvao** [comment]
> The process will replace all but one location of files and folders that are currently in multiple locations. The files and folders will be replaced with shortcuts.

That suggests a solution is to add all drives to the Workflow. It should then find the non-shortcut version, which is what matters. Have you tried that approach?

Could you also provide me with samples of these shortcuts as they appear on your Mac? Preferably at least one for a file and one for a folder. Google’s page doesn’t provide any technical information on what those actually are, and without inspecting some I can’t say for sure if they can be supported or not.

**Comment by SimonGZ** [comment]
Re: the first suggestion
To clarify, these aren't shortcuts to files in other drives. All the files are in my drive, but many are in Shared Folders, which unfortunately appear as shortcut folders on my Mac. In fact, the only problem seems to be with these Shared Folders as individually shared files appear as regular gdoc or ghseet files as they always did.

The filetype can't be uploaded as it's just an alias/symbolic link, but here's some info that should be useful: Each shortcut is actually an alias that leads to a hidden shortcut folder in Volumes/GoogleDrive called `.shortcut-targets-by-id`.

So the Get Info for a shared folder called "Hunt the Truth" looks like...
<img width="377" alt="Screen Shot 2022-06-15 at 12 20 12 PM" src="https://user-images.githubusercontent.com/1120980/173907685-8400bf8d-0e3f-45b3-83fe-c84b4e11f66b.png">

And in that hidden folder is the normal "Hunt the Truth" folder which is in turn filled with all the usual `.gdoc` files.

So perhaps it would be possible for the script to see when there's an alias and just follow it to the proper folder location... (edit: Or even just search the .shortcut-targets-by-id folder in addition to the regular Drive folder while ignoring the outer level of id-named folders)

**Comment by vitorgalvao** [comment]
> The filetype can't be uploaded

If it’s zipped first, it should work.

> it's just an alias/symbolic link

Symlinks and Finder aliases are different (though they both show as `Alias` in Get Info). I wanted to inspect them precisely to find which, or if a third weird thing Google was doing.

> see when there's an alias and just follow it to the proper folder location

The Workflow does see but [purposefully ignores symlinks](https://github.com/alfredapp/google-drive-workflow/blob/b1d5214821a134727dca420480125525613f1985/Workflow/rebuild_cache#L45) because handling them in such a context could lead to loops.

> Or even just search the .shortcut-targets-by-id folder in addition to the regular Drive folder while ignoring the outer level of id-named folders

I’d like to avoid that (at least for for now) because Google Drive is undergoing a lot of changes. In addition to what you’re seeing they’re also [switching to the File Provider API](https://support.google.com/drive/answer/12178485), which you’re not yet on (your drive would be in a different location). It’s not yet clear what all the changes entail, since apparently [Spotlight will be able to again index the Drive, but not everything](https://support.google.com/drive/answer/12178485#zippy=%2Chow-does-this-functionality-differ-from-what-i-had-before).

From the information above, if you change the Workflow’s `google_drive_path` to `/Volumes/GoogleDrive` (the default), your files will be found because the `.shortcut-targets-by-id` directory will be included. That’s the proper solution until Google finishes the transition, at which point we can properly evaluate what changed and adapt the Workflow.
